### ISSUE TITLE
Tag for release 0.0.7 missing

### ISSUE THREAD

**Issue by keeba0** [tvbarthel/CameraColorPicker#10]
There is a release of version 0.0.7 of Camera Color Picker in Play Store that has no tag here on GitHub. In order to release the app on F-Droid it would be nice to have tags for every version that should be released (every stable version). The process could then be automated.

Thanks!

**Comment by vbarthel-fr** [comment]
Hi @keeba0 

thanks for your interest in CameraColorPicker =)

I have just published a new tag for the release 0.0.7 https://github.com/tvbarthel/CameraColorPicker/releases/tag/v0.0.7

At the beginning of the project, we wanted to publish this app on F-Droid but sadly we never took the time to do it. In fact the product flavor "foss" is intended for F-Droid.

https://github.com/tvbarthel/CameraColorPicker/blob/master/CameraColorPicker/app/build.gradle#L26

We will definitely try to maintain tags for each release version =)

Have a great day,

Vincent.
