### ISSUE TITLE
[Palette] drop touch when color number >=2

### ISSUE THREAD

**Issue by tbarthel-fr** [tvbarthel/CameraColorPicker#23]
you must stay on the palette page + FAB bounce when color number >= 2 in order to indicate you how to create a palette.

**Comment by vbarthel-fr** [comment]
@tbarthel-fr 7e0be6d473576bb98533d0bc31297bc6589caa31 fixes this issue, right?

**Comment by tbarthel-fr** [comment]
@vbarthel-fr no shit Sherlock.
