### ISSUE TITLE
Implement openintents PICK_COLOR action

### ISSUE THREAD

**Issue by travisfw** [tvbarthel/CameraColorPicker#33]
Using your camera to pick a color is a great capability that could be utilized by other apps. The pull request https://github.com/tvbarthel/CameraColorPicker/pull/32 is one way to do that implementation that does not get in the way of the existing behavior of CameraColorPicker. Should that be merged in, or is there a better solution?

**Comment by vbarthel-fr** [comment]
Thanks again @travisfw 

I have just merged your PR #32  =)
